version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
      jobs:
        - aws-ecr/build-and-push-image:
            # XXXXXXXXXXX.dkr.ecr.<YOUR REGION>.amazonaws.com
            account-url: AWS_ECR_ACCOUNT_URL
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            region: AWS_DEFAULT_REGION
            repo: '${MY_APP_PREFIX}'
            tag: 'app-b-${CIRCLE_SHA1}'
            path: ./
